setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: localhost
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0
  wandb_config:
    project: DeepLoc_cls10
    name: esmc_300m

model:
  model_py_path: esmc/esmc_classification_model
  kwargs:
    model_name: esmc_300m
    num_labels: 10
    freeze_backbone: false
    device: cuda
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 2.0e-5
    on_use: false

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

dataset:
  dataset_py_path: esmc/esmc_classification_dataset
  dataloader_kwargs:
    batch_size: 1
    num_workers: 2

  train_lmdb: /content/saprot/LMDB/DeepLoc/cls10/normal/train
  valid_lmdb: /content/saprot/LMDB/DeepLoc/cls10/normal/valid
  test_lmdb: /content/saprot/LMDB/DeepLoc/cls10/normal/test
  kwargs:
    model_name: esmc_300m

Trainer:
  max_epochs: 5
  log_every_n_steps: 1
  strategy:
    find_unused_parameters: True
  logger: False
  enable_checkpointing: false
  val_check_interval: 0.5
  accelerator: gpu
  devices: 1
  num_nodes: 1
  accumulate_grad_batches: 1
  precision: 16-mixed
  num_sanity_val_steps: 0


