setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0
    MASTER_ADDR: localhost
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0

model:
  # Example: choose one of the registered models
  # model_py_path: saprot/saprot_classification_model
  kwargs:
    load_pretrained: True
    # num_labels: 2

  lr_scheduler_kwargs:
    class: ConstantLRScheduler
    init_lr: 2.0e-5

dataset:
  # Example: choose one of the registered datasets
  # dataset_py_path: saprot/saprot_classification_dataset
  dataloader_kwargs:
    batch_size: 1
    num_workers: 2
  kwargs:
    # tokenizer: westlake-repl/SaProt_35M_AF2
    plddt_threshold: null

Trainer:
  max_epochs: 1
  log_every_n_steps: 1
  strategy:
    class: auto
  logger: False
  enable_checkpointing: false
  val_check_interval: 0.5
  accelerator: gpu
  devices: 1
  num_nodes: 1
  accumulate_grad_batches: 1
  precision: 16
  num_sanity_val_steps: 0


