setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: localhost
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0
  # wandb_config:
  #   project: DeepLoc_cls2
  #   name: SaProt_35M_AF2

model:
#    Which model to use
  # model_py_path: saprot/saprot_classification_model
  kwargs:
#    Arguments to initialize the specific class
    # config_path: westlake-repl/SaProt_35M_AF2
    load_pretrained: True
    # num_labels: 2

#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    class: ConstantLRScheduler
    init_lr: 2.0e-5


#  save_path: /content/saprot/weights/DeepLoc/cls2/SaProt_35M_AF2.pt


dataset:
#    Arguments to initialize the basic class LMDBDataset
  # dataset_py_path: saprot/saprot_classification_dataset
  dataloader_kwargs:
    batch_size: 1
    num_workers: 2

  # train_lmdb: /content/saprot/LMDB/DeepLoc/cls2/foldseek/train
  # valid_lmdb: /content/saprot/LMDB/DeepLoc/cls2/foldseek/valid
  # test_lmdb: /content/saprot/LMDB/DeepLoc/cls2/foldseek/test
#    Arguments to initialize the specific class
  kwargs:
    # tokenizer: westlake-repl/SaProt_35M_AF2
    plddt_threshold: null


#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
  max_epochs: 2
  log_every_n_steps: 1
  strategy: 
    class: auto
  logger: False
  enable_checkpointing: false
  val_check_interval: 0.5
  accelerator: gpu
  devices: 1
  num_nodes: 1
  accumulate_grad_batches: 1
  precision: 16
  num_sanity_val_steps: 0
